### ISSUE TITLE
I'm not very sure about the q(|)

### ISSUE THREAD

**Issue by herbertchen1** [wujsAct/fine-grained-entity-typing-Hier-Denoise#2]
q似乎是一个可学习的，基于样本的函数，请问这个函数是如何学到的，如果是纯粹基于tree的话，那就是启发式定义了一下，各个类型的权重。
由于这部分内容并没有很清楚的说明。。。。
此外，我发现Normalized Type Hierarchy 实际上是NFETC的另外一种表述，而2.3小节的两个假设也是NFETC的假设，可能不太需要过多的解释。

**Comment by herbertchen1** [comment]
我理解的没错的话，q就是基于tree，只是alpha对于每个样本有加和为1的约束，最终q作为转移概率是可以学出来的。

**Comment by herbertchen1** [comment]
而这个约束是通过softmax实现的，具体的细节就不太明白了

**Comment by wujsAct** [comment]
对，你的理解是正确的，这个q是基于树的，每个约束是通过softmax实现的，值得注意的是我们的方法，是基于instance的，即对于每个noisy sample我们都要学习一个q，测试的时候，是没有这个q的。
